import { apiClient } from "../api/client";
import { offlineEngine } from "../services/sync";
import type { ListResult, QueryOptions, RepositoryResult } from "./base";
import type { EntityId, Message, MessageAttachment, MessageConversation, MessageModerationMetadata } from "../types/domain";

const conversationsPath = "/messageConversations";
const messagesPath = "/messages";
const now = () => new Date().toISOString();
const source = (value: string): RepositoryResult<unknown>["source"] => value === "mock" || value === "cache" ? value : "remote";

export type CreateConversationInput = Omit<MessageConversation, "id" | "createdAt" | "updatedAt" | "status" | "readByUserIds" | "archivedByUserIds"> & Partial<Pick<MessageConversation, "id" | "createdAt" | "updatedAt" | "status" | "readByUserIds" | "archivedByUserIds">>;
export type SendMessageInput = { conversationId: EntityId; organizationId?: EntityId; senderUserId: EntityId; body: string; attachments?: MessageAttachment[]; moderation?: MessageModerationMetadata; kind?: Message["kind"]; id?: EntityId; createdAt?: string; };
export type UpdateMessageInput = Partial<Pick<Message, "body" | "attachments" | "moderation" | "status">>;

const demoConversations: MessageConversation[] = [
  { id: "conv-trainer-member", organizationId: "org_demo", title: "Jordan Lee", type: "direct", participantUserIds: ["trainer_demo", "member_demo"], trainerId: "trainer_demo", memberId: "member_demo", status: "active", readByUserIds: ["trainer_demo"], archivedByUserIds: [], lastMessagePreview: "Can you review my form check attachment?", lastMessageAt: now(), realtimeTopic: "messaging:conv-trainer-member", createdAt: now(), updatedAt: now() },
  { id: "conv-team-announcements", organizationId: "org_demo", title: "Team Announcements", type: "team_announcement", participantUserIds: ["trainer_demo", "member_demo"], teamId: "team_strength", trainerId: "trainer_demo", status: "active", readByUserIds: [], archivedByUserIds: [], lastMessagePreview: "Saturday lift block starts at 9 AM.", lastMessageAt: now(), realtimeTopic: "messaging:team_strength", createdAt: now(), updatedAt: now() },
  { id: "conv-system", organizationId: "org_demo", title: "System", type: "system", participantUserIds: ["member_demo"], status: "active", readByUserIds: ["member_demo"], archivedByUserIds: [], lastMessagePreview: "Your weekly progress report is ready.", lastMessageAt: now(), realtimeTopic: "messaging:system", createdAt: now(), updatedAt: now() },
];
const demoMessages: Message[] = [
  { id: "msg-1", organizationId: "org_demo", conversationId: "conv-trainer-member", senderUserId: "member_demo", recipientUserIds: ["trainer_demo"], body: "Can you review my form check attachment?", kind: "direct", status: "delivered", attachments: [{ id: "att-1", name: "squat-form.mov", mimeType: "video/quicktime", sizeBytes: 8421000, storagePath: "mock://attachments/squat-form.mov", uploadedByUserId: "member_demo", createdAt: now() }], moderation: { status: "clear", flags: [], reviewedBy: "automated", reviewedAt: now() }, createdAt: now(), updatedAt: now() },
  { id: "msg-2", organizationId: "org_demo", conversationId: "conv-team-announcements", senderUserId: "trainer_demo", recipientUserIds: ["member_demo"], body: "Saturday lift block starts at 9 AM. Bring water and log readiness before arrival.", kind: "announcement", status: "sent", attachments: [], moderation: { status: "clear", flags: [], reviewedBy: "automated", reviewedAt: now() }, createdAt: now(), updatedAt: now() },
  { id: "msg-3", organizationId: "org_demo", conversationId: "conv-system", senderUserId: "system", recipientUserIds: ["member_demo"], body: "Your weekly progress report is ready.", kind: "system", status: "read", attachments: [], moderation: { status: "clear", flags: [], reviewedBy: "system", reviewedAt: now() }, createdAt: now(), updatedAt: now() },
];

export class MessagingRepository {
  async listConversations(options?: QueryOptions & { userId?: EntityId; includeArchived?: boolean }): Promise<RepositoryResult<ListResult<MessageConversation>>> {
    const response = await apiClient.get<ListResult<MessageConversation>>(conversationsPath, { headers: options?.organizationId ? { "x-organization-id": options.organizationId } : undefined });
    const items = (response.data.items?.length ? response.data.items : demoConversations).filter((c) => (!options?.organizationId || c.organizationId === options.organizationId || c.organizationId === "org_demo") && (!options?.userId || c.participantUserIds.includes(options.userId) || c.trainerId === options.userId || c.memberId === options.userId) && (options?.includeArchived || c.status !== "archived"));
    return { data: { items: items.slice(0, options?.limit ?? items.length), nextCursor: response.data.nextCursor }, source: source(response.source) };
  }
  async findConversationById(id: EntityId) { const r = await apiClient.get<MessageConversation | null>(`${conversationsPath}/${id}`); return { data: r.data ?? demoConversations.find((c) => c.id === id) ?? null, source: source(r.source) }; }
  async createConversation(input: CreateConversationInput) { const t = now(); const record: MessageConversation = { ...input, id: input.id ?? crypto.randomUUID(), status: input.status ?? "active", readByUserIds: input.readByUserIds ?? [], archivedByUserIds: input.archivedByUserIds ?? [], realtimeTopic: input.realtimeTopic ?? `messaging:${input.id ?? crypto.randomUUID()}`, createdAt: input.createdAt ?? t, updatedAt: input.updatedAt ?? t }; const r = await apiClient.post<MessageConversation, MessageConversation>(conversationsPath, record, { queueWhenOffline: true }); return { data: r.data ?? record, source: source(r.source) }; }
  async archiveConversation(id: EntityId, userId?: EntityId) { const patch = { status: "archived" as const, archivedByUserIds: userId ? [userId] : [], deletedAt: now(), updatedAt: now() }; try { const r = await apiClient.patch<MessageConversation, typeof patch>(`${conversationsPath}/${id}`, patch, { queueWhenOffline: true }); return { data: r.data, source: source(r.source) }; } catch { const existing = demoConversations.find((c) => c.id === id); return { data: { ...existing!, ...patch }, source: "mock" as const }; } }
  async markRead(id: EntityId, userId: EntityId, read = true) { const existing = (await this.findConversationById(id)).data; const ids = new Set(existing?.readByUserIds ?? []); read ? ids.add(userId) : ids.delete(userId); const patch = { readByUserIds: Array.from(ids), updatedAt: now() }; try { const r = await apiClient.patch<MessageConversation, typeof patch>(`${conversationsPath}/${id}`, patch, { queueWhenOffline: true }); return { data: r.data ?? { ...existing!, ...patch }, source: source(r.source) }; } catch { return { data: { ...existing!, ...patch }, source: "mock" as const }; } }
  async listMessages(conversationId: EntityId): Promise<RepositoryResult<ListResult<Message>>> { const r = await apiClient.get<ListResult<Message>>(messagesPath); const items = (r.data.items?.length ? r.data.items : demoMessages).filter((m) => m.conversationId === conversationId && m.status !== "archived"); return { data: { items }, source: source(r.source) }; }
  async sendMessage(input: SendMessageInput) { const t = now(); const record: Message = { id: input.id ?? crypto.randomUUID(), organizationId: input.organizationId, conversationId: input.conversationId, senderUserId: input.senderUserId, recipientUserIds: [], body: input.body, kind: input.kind ?? "direct", status: navigator.onLine ? "sent" : "queued", attachments: input.attachments ?? [], moderation: input.moderation ?? { status: "clear", flags: [], reviewedBy: "automated", reviewedAt: t }, createdAt: input.createdAt ?? t, updatedAt: t }; const r = await apiClient.post<Message, Message>(messagesPath, record, { queueWhenOffline: true }); return { data: r.data ?? record, source: source(r.source) }; }
  async editMessage(id: EntityId, input: UpdateMessageInput) { const patch = { ...input, editedAt: now(), updatedAt: now() }; try { const r = await apiClient.patch<Message, typeof patch>(`${messagesPath}/${id}`, patch, { queueWhenOffline: true }); return { data: r.data, source: source(r.source) }; } catch { const existing = demoMessages.find((m) => m.id === id); return { data: { ...existing!, ...patch }, source: "mock" as const }; } }
  async searchMessages(query: string, options?: { conversationId?: EntityId }) { const r = await apiClient.get<ListResult<Message>>(messagesPath); const pool = r.data.items?.length ? r.data.items : demoMessages; const q = query.trim().toLowerCase(); return { data: { items: pool.filter((m) => (!options?.conversationId || m.conversationId === options.conversationId) && (!q || m.body.toLowerCase().includes(q) || m.attachments?.some((a) => a.name.toLowerCase().includes(q)))) }, source: source(r.source) }; }
  getOfflineQueue() { return offlineEngine.getQueue().filter((w) => w.entity.includes("message")); }
}
export const messagingRepository = new MessagingRepository();
