import { apiClient } from "../api/client";
import { offlineEngine, type QueuedWrite } from "../services/sync";
import type { EntityId, IsoDateTimeString } from "../types/domain";
import type { RepositoryResult } from "./base";

export type RelationshipStatus = "active" | "invited" | "pending" | "paused" | "ended" | "archived";
export type RelationshipKind = "consumer" | "trainer" | "gym" | "enterprise_gym";
export type JoinPath = "personal_signup" | "trainer_onboarding_link" | "gym_enterprise_onboarding_link";
export type DataAccessScope = "user_owned" | "gym_visible" | "trainer_visible" | "shared" | "revoked" | "export_ready";

export interface AccountOwnershipModel { userId: EntityId; permanence: "permanent"; personalDataOwner: "user"; consumerOnlyAllowed: boolean; canLeaveRelationshipsWithoutDataLoss: boolean; exportReady: boolean; }
export interface TenantBranding { id: EntityId; ownerType: "consumer" | "trainer" | "gym"; ownerId: EntityId; brandName: string; logoMedia: { placeholder: string; url?: string; alt: string }; primaryColor: string; accentColor: string; domain?: string; subdomain?: string; featureToggles: Record<string, boolean>; rolePermissions: Record<string, string[]>; appConfiguration: Record<string, string | boolean>; onboardingSettings: { defaultPath: JoinPath; requireInviteCode: boolean; welcomeMessage: string }; billingMetadata: Record<string, string>; notificationMetadata: Record<string, string>; updatedAt: IsoDateTimeString; }
export interface TenantRelationship { id: EntityId; userId: EntityId; kind: RelationshipKind; status: RelationshipStatus; displayName: string; organizationId?: EntityId; gymId?: EntityId; trainerId?: EntityId; role: string; permissions: string[]; accessScopes: DataAccessScope[]; inviteCodeMetadata?: Record<string, string>; invitationAcceptanceMetadata?: Record<string, string>; transferMetadata?: Record<string, string>; revokedAccessMetadata?: Record<string, string>; subscriptionGrant?: "none" | "consumer" | "trainer" | "gym_enterprise"; createdAt: IsoDateTimeString; updatedAt: IsoDateTimeString; endedAt?: IsoDateTimeString; archivedAt?: IsoDateTimeString; }
export interface ConsumerSubscription { id: EntityId; userId: EntityId; status: "active" | "trialing" | "paused" | "cancelled"; independentFromTenantRelationships: boolean; entitlement: string; updatedAt: IsoDateTimeString; }
export interface DataAccessRule { id: EntityId; label: string; scope: DataAccessScope; owner: "user" | "gym" | "trainer" | "shared"; visibleTo: string[]; revoked: boolean; exportReady: boolean; metadata: Record<string, string>; }
export interface TenancySnapshot { ownership: AccountOwnershipModel; joinPath: JoinPath; activeTenantContextId?: EntityId; activeTrainerContextId?: EntityId; relationships: TenantRelationship[]; consumerSubscription: ConsumerSubscription; branding: TenantBranding[]; dataAccessRules: DataAccessRule[]; pendingSync: string[]; saveStatus: string; }

const relationshipsPath = "/tenancyRelationships";
const brandingPath = "/tenantBranding";
const settingsPath = "/tenantSettings";
const now = () => new Date().toISOString();
const source = (name: string): RepositoryResult<unknown>["source"] => name === "mock" || name === "cache" ? name : "remote";

export class TenancyRepository {
  seedSnapshot(userId: EntityId = "user-demo"): TenancySnapshot {
    const timestamp = now();
    const gym: TenantRelationship = { id: "rel-gym-demo", userId, kind: "enterprise_gym", status: "active", displayName: "Summit Strength Collective", organizationId: "org-demo", gymId: "gym-demo", role: "member", permissions: ["classes:view", "coaching:receive"], accessScopes: ["gym_visible", "shared"], inviteCodeMetadata: { codeType: "enterprise", campaign: "founding-members" }, invitationAcceptanceMetadata: { acceptedAt: timestamp, acceptedVia: "gym_enterprise_onboarding_link" }, transferMetadata: { transferable: "true", lastTransferAt: "none" }, subscriptionGrant: "gym_enterprise", createdAt: timestamp, updatedAt: timestamp };
    const trainer: TenantRelationship = { id: "rel-trainer-demo", userId, kind: "trainer", status: "active", displayName: "Avery Coaching", trainerId: "trainer-demo", role: "client", permissions: ["program:view", "check_in:submit"], accessScopes: ["trainer_visible", "shared"], inviteCodeMetadata: { codeType: "trainer", trainerSlug: "avery" }, invitationAcceptanceMetadata: { acceptedAt: timestamp, acceptedVia: "trainer_onboarding_link" }, transferMetadata: { previousTrainerId: "none", reason: "member_requested" }, subscriptionGrant: "trainer", createdAt: timestamp, updatedAt: timestamp };
    return { ownership: { userId, permanence: "permanent", personalDataOwner: "user", consumerOnlyAllowed: true, canLeaveRelationshipsWithoutDataLoss: true, exportReady: true }, joinPath: "personal_signup", activeTenantContextId: gym.id, activeTrainerContextId: trainer.id, relationships: [gym, trainer, { id: "rel-consumer-demo", userId, kind: "consumer", status: "active", displayName: "GymCord Personal", role: "owner", permissions: ["data:export", "subscription:manage"], accessScopes: ["user_owned", "export_ready"], subscriptionGrant: "consumer", createdAt: timestamp, updatedAt: timestamp }], consumerSubscription: { id: "consumer-sub-demo", userId, status: "active", independentFromTenantRelationships: true, entitlement: "GymCord personal history + Atlas baseline", updatedAt: timestamp }, branding: [this.defaultConsumerBrand(), this.gymBrand(timestamp), this.trainerBrand(timestamp)], dataAccessRules: this.defaultDataRules(), pendingSync: this.getOfflineQueue().map((item) => item.id), saveStatus: "seeded" };
  }

  async loadSnapshot(userId: EntityId = "user-demo"): Promise<RepositoryResult<TenancySnapshot>> {
    const seeded = this.seedSnapshot(userId);
    try {
      const [relationships, branding] = await Promise.all([apiClient.get<{ items: TenantRelationship[] }>(relationshipsPath), apiClient.get<{ items: TenantBranding[] }>(brandingPath)]);
      return { data: { ...seeded, relationships: relationships.data.items.length ? relationships.data.items.filter((item) => item.userId === userId) : seeded.relationships, branding: branding.data.items.length ? branding.data.items : seeded.branding, pendingSync: this.getOfflineQueue().map((item) => item.id), saveStatus: "loaded" }, source: source(relationships.source) };
    } catch { return { data: seeded, source: "mock" }; }
  }

  async updateRelationship(id: EntityId, input: Partial<TenantRelationship>): Promise<RepositoryResult<TenantRelationship>> { const payload = { ...input, updatedAt: now() }; const response = await apiClient.patch<TenantRelationship, typeof payload>(`${relationshipsPath}/${id}`, payload, { queueWhenOffline: true }); return { data: response.data ?? ({ id, ...payload } as TenantRelationship), source: source(response.source) }; }
  endRelationship(id: EntityId) { const timestamp = now(); return this.updateRelationship(id, { status: "ended", endedAt: timestamp, revokedAccessMetadata: { revokedAt: timestamp, defaultAction: "end_not_delete" } }); }
  archiveRelationship(id: EntityId) { const timestamp = now(); return this.updateRelationship(id, { status: "archived", archivedAt: timestamp }); }
  async saveBranding(input: TenantBranding): Promise<RepositoryResult<TenantBranding>> { const response = await apiClient.post<TenantBranding, TenantBranding>(brandingPath, { ...input, updatedAt: now() }, { queueWhenOffline: true }); return { data: response.data ?? input, source: source(response.source) }; }
  async saveTenantSettings(settings: Record<string, unknown>): Promise<RepositoryResult<Record<string, unknown>>> { const response = await apiClient.post<Record<string, unknown>, Record<string, unknown>>(settingsPath, { ...settings, updatedAt: now() }, { queueWhenOffline: true }); return { data: response.data ?? settings, source: source(response.source) }; }
  getOfflineQueue(): QueuedWrite[] { return offlineEngine.getQueue().filter((item) => [relationshipsPath, brandingPath, settingsPath].some((path) => item.entity === path || item.entity.startsWith(`${path}/`))); }

  defaultConsumerBrand(): TenantBranding { const timestamp = now(); return { id: "brand-consumer-default", ownerType: "consumer", ownerId: "gymcord", brandName: "GymCord", logoMedia: { placeholder: "GC", alt: "GymCord default logo placeholder" }, primaryColor: "#ff4fa0", accentColor: "#ff8a65", subdomain: "app", featureToggles: { atlasCoach: true, gymClasses: false, trainerPortal: false }, rolePermissions: { owner: ["data:export", "subscription:manage"] }, appConfiguration: { shell: "consumer", whiteLabel: false }, onboardingSettings: { defaultPath: "personal_signup", requireInviteCode: false, welcomeMessage: "Own your fitness history forever." }, billingMetadata: { subscriptionOwner: "consumer" }, notificationMetadata: { audience: "consumer" }, updatedAt: timestamp }; }
  private gymBrand(timestamp: string): TenantBranding { return { id: "brand-gym-demo", ownerType: "gym", ownerId: "org-demo", brandName: "Summit Strength", logoMedia: { placeholder: "SS", alt: "Summit logo metadata placeholder" }, primaryColor: "#75f0b2", accentColor: "#ff4fa0", domain: "summit.example", subdomain: "summit", featureToggles: { enterpriseBilling: true, roster: true, atlasCoach: true }, rolePermissions: { admin: ["members:invite", "branding:update"], trainer: ["clients:view"] }, appConfiguration: { shell: "white_label_gym", whiteLabel: true }, onboardingSettings: { defaultPath: "gym_enterprise_onboarding_link", requireInviteCode: true, welcomeMessage: "Join through your gym without giving up data ownership." }, billingMetadata: { subscriptionOwner: "gym_enterprise", grantsAccessOnly: "true" }, notificationMetadata: { senderName: "Summit Strength" }, updatedAt: timestamp }; }
  private trainerBrand(timestamp: string): TenantBranding { return { id: "brand-trainer-demo", ownerType: "trainer", ownerId: "trainer-demo", brandName: "Avery Coaching", logoMedia: { placeholder: "AC", alt: "Trainer logo metadata placeholder" }, primaryColor: "#7aa2ff", accentColor: "#75f0b2", subdomain: "avery", featureToggles: { checkIns: true, programs: true, enterpriseBilling: false }, rolePermissions: { trainer: ["programs:assign", "check_ins:review"], client: ["check_ins:submit"] }, appConfiguration: { shell: "trainer_invite", whiteLabel: true }, onboardingSettings: { defaultPath: "trainer_onboarding_link", requireInviteCode: true, welcomeMessage: "Accept trainer access while keeping your personal account." }, billingMetadata: { subscriptionOwner: "trainer", grantsCoachingAccessOnly: "true" }, notificationMetadata: { senderName: "Avery Coaching" }, updatedAt: timestamp }; }
  private defaultDataRules(): DataAccessRule[] { return ["user_owned", "gym_visible", "trainer_visible", "shared", "revoked", "export_ready"].map((scope) => ({ id: `rule-${scope}`, label: scope.replace(/_/g, " "), scope: scope as DataAccessScope, owner: scope === "user_owned" || scope === "export_ready" ? "user" : scope === "gym_visible" ? "gym" : scope === "trainer_visible" ? "trainer" : "shared", visibleTo: scope === "revoked" ? [] : ["user", scope.includes("gym") ? "gym" : "trainer"], revoked: scope === "revoked", exportReady: scope === "export_ready" || scope === "user_owned", metadata: { hardDeleteDefault: "false", revokePreservesHistory: "true" } })); }
}
export const tenancyRepository = new TenancyRepository();
