import { useEffect, useMemo, useState } from "react";
import { createWorkoutDay, programRepository, programTemplates, type Program, type ProgramTemplate } from "../../repositories";
import { ProgramAssignmentPanel } from "./ProgramAssignmentPanel";
import { ProgramEditor } from "./ProgramEditor";
import { ProgramList } from "./ProgramList";
import { ProgramStatusBar } from "./ProgramStatusBar";
import { ProgramTemplateGallery } from "./ProgramTemplateGallery";

const seedTrainerId = "trainer_demo";
function blankProgram(): Program { const at = new Date().toISOString(); return { id: crypto.randomUUID(), trainerId: seedTrainerId, organizationId: "org_demo", title: "New Program", description: "Describe the outcome, progression, and coaching notes.", goal: "Build consistency", difficulty: "beginner", durationWeeks: 8, status: "draft", schedule: [createWorkoutDay()], assignments: [], createdAt: at, updatedAt: at }; }
export function ProgramBuilder({ developer = false }: { developer?: boolean }) {
  const repository = useMemo(() => programRepository, []);
  const [programs, setPrograms] = useState<Program[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [source, setSource] = useState(repository.providerName); const [saveStatus, setSaveStatus] = useState("Loading programs…");
  const selected = programs.find((program) => program.id === selectedId);
  const pendingSync = repository.getOfflineQueue().filter((write) => write.status !== "synced").length;
  useEffect(() => { let active = true; repository.list({ organizationId: "org_demo" }).then((result) => { if (!active) return; const next = result.data.items; setPrograms(next); setSelectedId(next[0]?.id); setSource(result.source === "remote" ? "supabase" : result.source); setSaveStatus("Programs loaded through repository."); }).catch((error: Error) => setSaveStatus(`Repository fallback: ${error.message}`)); return () => { active = false; }; }, [repository]);
  async function commit(next: Program) { setPrograms((items) => items.map((item) => item.id === next.id ? next : item)); setSaveStatus("Saving optimistic update…"); const result = await repository.update(next.id, next); setPrograms((items) => items.map((item) => item.id === next.id ? result.data : item)); setSaveStatus(`Saved from ${result.source}.`); }
  async function create(program: Program = blankProgram()) { setPrograms((items) => [program, ...items]); setSelectedId(program.id); const result = await repository.create(program); setPrograms((items) => items.map((item) => item.id === program.id ? result.data : item)); setSaveStatus(`Created from ${result.source}.`); }
  async function duplicate(id: string) { const result = await repository.duplicate(id); setPrograms((items) => [result.data, ...items]); setSelectedId(result.data.id); setSaveStatus(`Duplicated as ${result.data.title}.`); }
  function useTemplate(template: ProgramTemplate) { const base = blankProgram(); void create({ ...base, title: template.title, description: template.description, goal: template.goal, difficulty: template.difficulty, durationWeeks: template.weeks, schedule: template.schedule, templateId: template.id }); }
  async function publish() { if (!selected) return; const result = await repository.publish(selected.id); setPrograms((items) => items.map((item) => item.id === selected.id ? result.data : item)); setSaveStatus("Program published."); }
  async function assign(memberId: string, startsOn: string) { if (!selected) return; const result = await repository.assign(selected.id, memberId, startsOn); setPrograms((items) => items.map((item) => item.id === selected.id ? result.data : item)); setSaveStatus(`Assigned to ${memberId}.`); }
  return <main className="program-builder-shell"><header className="hero-card"><p className="eyebrow">{developer ? "Developer" : "Trainer"} Program Builder</p><h1>Build, publish, and assign training programs</h1><p>Repository-backed program management for mock and Supabase provider modes.</p></header><ProgramStatusBar program={selected} pendingSync={pendingSync} saveStatus={saveStatus} onPublish={publish} onDraft={() => selected && void repository.saveDraft(selected.id, selected).then((result) => { setPrograms((items) => items.map((item) => item.id === selected.id ? result.data : item)); setSaveStatus("Draft saved."); })} /><section className="grid two-columns"><ProgramList programs={programs} selectedId={selectedId} onSelect={setSelectedId} onCreate={() => void create()} onDuplicate={(id) => void duplicate(id)} /><div><section className="panel-card"><p className="eyebrow">Diagnostics</p><ul className="check-list"><li>Active provider: {source}</li><li>Programs loaded: {programs.length}</li><li>Selected program: {selected?.title ?? "None"}</li><li>Draft/publish status: {selected?.status ?? "n/a"}</li><li>Pending sync: {pendingSync}</li><li>Offline queue: {repository.getOfflineQueue().length}</li><li>Save status: {saveStatus}</li></ul></section><ProgramAssignmentPanel program={selected} onAssign={(memberId, startsOn) => void assign(memberId, startsOn)} /></div></section><ProgramEditor program={selected} onChange={(next) => void commit(next)} /><ProgramTemplateGallery templates={programTemplates} onUse={useTemplate} /></main>;
}
